Site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('user/', include('user.urls')),
]

principal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.login, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('rec_senha/', views.recuperar_senha, name='rec_senha'),
    path('alterar_senha/', views.alterar_senha, name='alterar_senha'),
    path('perfil/', views.perfil, name='perfil'),
    path('404', views.er404, name='404'),
    path('403', views.er403, name='403'),
    path('500', views.er500, name='500'),
    path('gestor/', views.gestor_page, name='gestor'),
    path('logout/', views.logout_sessao, name='logout'),
    path('edicao/<str:id>', views.edicao_dados, name='edicao'),
    path('deletar/<str:id>', views.deletar_conta, name='deletar'),
    path('cadastro_endereco/', views.cadastroEndereco, name='cadastro_endereco')
]

principal/models.py
from django.db import models
import random

class Usuario(models.Model):
    id = models.CharField(max_length=8, verbose_name=u'ID', primary_key=True, blank=True, editable=False)
    def gerar_id(self):
        return ''.join(random.choices('0123456789', k=8))
    def save(self, *args, **kwargs):
        if not self.id:
            self.id = self.gerar_id()
        super().save(*args, **kwargs)
    nome = models.CharField(max_length=30, verbose_name=u'Nome')
    NIVEL = [('Padrão', 'Padrão'),
             ('Gestor', 'Gestor'),
    ]
    GENERO = [('M', 'Masculino'),
              ('F', 'Feminino'),
              ('Transgênero', 'Transgênero'),
              ('Não binário', 'Não binário'),
        ]
    genero = models.CharField(max_length=11, verbose_name=u'Gênero', choices=GENERO)
    senha = models.CharField(max_length=72, verbose_name=u'Senha', unique=True)
    cpf = models.CharField(max_length=11, verbose_name=u'CPF', unique=True)
    email = models.EmailField(max_length=40,verbose_name=u'Email', )
    telefone = models.CharField(max_length=11, verbose_name=u'Telefone', null=True, blank=True)
    data_nascimento = models.DateField(verbose_name=u'Data de nascimento')
    nivel = models.CharField(verbose_name=u'Nivel de usuario:', choices=NIVEL)
    
    def __str__(self):
        return self.nome
    
class Endereco(models.Model):
    id = models.CharField(max_length=5, verbose_name=u'ID', primary_key=True, blank=True)
    def gerar_id(self):
        return ''.join(random.choices('0123456789', k=5))
    def save(self, *args, **kwargs):
        if not self.id:
            self.id = self.gerar_id()
        super().save(*args, **kwargs)
    UF = [('AL', 'Alagoas'),
          ('AC','Acre'),
          ('AP','Amapá'),
          ('AM','Amazonas'),
          ('BA','Bahia'),
          ('CE', 'Ceará')
        ]
    uf = models.CharField(max_length=2, verbose_name=u'UF', choices=UF)
    cidade = models.CharField(max_length=29, verbose_name=u'Cidade')
    bairro = models.CharField(max_length=50, verbose_name=u'Bairro')
    rua = models.CharField(max_length=50, verbose_name=u'Rua')
    n = models.CharField(max_length=10, verbose_name=u'N°')
    complemento = models.CharField(max_length=100, verbose_name=u'Complemento(opcional)', null=True, blank=True)
    cliente_id = models.ForeignKey(Usuario, on_delete=models.CASCADE, editable=False)

    def __str__(self):
        return str(self.cliente_id)

principal/forms.py
from django import forms
from .models import Usuario, Endereco
from django.forms import ValidationError
import re
import bcrypt 

class Cadastro(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('nome', 'genero', 'email', 'cpf', 'senha', 'telefone', 'data_nascimento', 'nivel')

    def clean_nome(self):
        nome = self.cleaned_data['nome']
        if len(nome) < 4:
            raise ValidationError('O nome tem que ter no mínimo 4 letras')
        else:
            return nome.upper()[0]
        
    def clean_cpf(self):
        cpf = self.cleaned_data['cpf']
        if len(cpf) < 11:
            raise ValidationError('Digite um CPF válido')
        else:
            return cpf
        
    def clean_senha(self):
        senha = self.cleaned_data.get('senha')
        if len(senha) < 8:
            raise ValidationError('Senha precisa ter no mínimo 8 caracteres')
        if not re.search(r'[a-z]', senha):
            raise ValidationError('Tem que conter no minimo uma letra minuscula')
        if not re.search(r'[A-Z]', senha):
            raise ValidationError('Tem que conter no minimo uma letra maiuscula')
        if not re.search(r'[0-9]', senha):
            raise ValidationError('Tem que conter no minimo um número')
        if not re.search(r'[!@#$%^&*=(),.:;?{}[\]\\|<>/~_+-]', senha):
            raise ValidationError('Tem que conter no minimo um simbolo')
        hashed_password = bcrypt.hashpw(senha.encode('utf-8'), bcrypt.gensalt())
        return hashed_password.decode('utf-8')
    
    def clean_email(self):
        email = self.cleaned_data['email']
        emails_validos = (r'@(gmail\.com|outlook\.com|hotmail\.com|yahoo\.com|'
                          r'uol\.com\.br|bol\.com\.br|terra\.com\.br|globomail\.com)$')
        if not re.search(emails_validos, email):
            raise ValidationError('Digite um email válido')
        else:
            return email
        
class Endereco(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ('uf', 'cidade', 'bairro', 'rua', 'n', 'complemento')

principal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib import messages
from .models import Usuario
from .forms import Cadastro, Endereco
from .decorador import usuario_requisicao
import bcrypt

@usuario_requisicao()
def index(request):
    return render(request, 'html/index.html')

def login(request):
    erro = None
    if request.method == 'POST':
        email = request.POST.get('email') 
        senha = request.POST.get('senha')
        auth_usuario = Usuario.objects.filter(email=email).first()
        if auth_usuario and bcrypt.checkpw(senha.encode('utf-8'), auth_usuario.senha.encode('utf-8')):
            request.session['id'] = auth_usuario.id
            if auth_usuario.nivel == 'Padrão':
                return redirect('index')
            elif auth_usuario.nivel == 'Gestor':
                return redirect('gestor')
        erro = 'Eamil ou senha inválidos'

    return render(request, 'html/login.html', {'erro': erro})

def cadastro(request):
    if request.method == 'POST':
        form = Cadastro(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = Cadastro()
    return render(request, 'html/cadastro.html', {'form': form})

@usuario_requisicao()
def cadastroEndereco(request):
   return render(request, 'html/cadastro_endereco')
   """def cadastroEndereco(request):
    if request.method == 'POST':
        form_end = Endereco(request.POST)
        if form_end.is_valid():
            endereco = form_end.save(commit=False)
            if isinstance(request.user, Usuario):
                endereco.cliente_id = request.user  
                endereco.save()
                return redirect('index')
            else:
                form_end.add_error(None, 'Usuário não está autenticado ou não é válido.')
    else:
        form_end = Endereco()
    return render(request, 'html/cadastro_endereco.html', {
        'form_end': form_end
    })"""

def recuperar_senha(request):
    return render(request, 'html/rec_senha.html')

def alterar_senha(request):
    return render(request, 'html/alterar_senha.html')

@usuario_requisicao()
def perfil(request):
    user_id = request.session.get('id')
    if not user_id:
        return redirect('login')
    dados = Usuario.objects.get(id=user_id)
    return render(request, 'html/perfil.html', {'dados': dados})

def er404(request):
    return render(request, 'html/er404.html')

def er403(request):
    return render(request, 'html/er403.html')

def er500(request):
    return render(request, 'html/er500.html')

@usuario_requisicao(nivel='Gestor')
def gestor_page(request):
    return render(request, 'html/gestor_page.html')

@usuario_requisicao()
def logout_sessao(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Você saiu com sucesso!")
    return redirect('login')

@usuario_requisicao()
def edicao_dados(request, id):
    edicao = get_object_or_404(Usuario, pk=id)
    form = Cadastro(instance=edicao)
    if request.method == 'POST':
        form = Cadastro(request.POST, instance=edicao)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados atualizados com sucesso')
            return redirect('login')
        else:
            messages.error(request, 'Erro na alteração dos dados, verifique se foram alterados corretamente')
            return render(request, 'html/edicao_dados.html', {'form': form, 'edicao': edicao})
    else:
        return render(request, 'html/edicao_dados.html', {'form': form, 'edicao': edicao})
    
@usuario_requisicao()
def deletar_conta(request, id):
    deletar = get_object_or_404(Usuario, pk=id)
    deletar.delete()
    messages.success(request, 'Conta excluida com sucesso')
    return redirect('login')

principal/templates/html/alterar_senha.html
{% extends "base.html" %}
{% load static %}
{% block title %}Alterar Senha{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
<link rel="stylesheet"  href="{% static 'css/alterar_senha.css' %}">
<div class="container mt-5">
    <h1>Alterar Senha</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="email" class="form-label">E-mail:</label>
            <input type="email" class="form-control" id="email" name="email">
            <br>
            <label for="email" class="form-label">Nova senha:</label>
            <input type="password" class="form-control" id="senha" name="senha">
            <br>
            <label for="email" class="form-label">Confirmar senha:</label>
            <input type="password" class="form-control" id="novasenha" name="novasenha">
        </div>
        <a href="{% url 'index' %}"><button type="submit" class="btn btn-primary">Alterar</button></a>
    </form>
</div>
{% endblock %}

principal/templates/html/cadastro.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <link rel="stylesheet"  href="{% static 'css/cadastro.css' %}">
    <h1>Cadastro</h1>
    <form method="POST" action="{% url 'cadastro' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Cadastrar</button>
    </form>
        <a href="{% url 'login' %}"><button type="button">Voltar</button></a>
    
{% endblock %}

principal/templates/html/cadastro_endereco.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <link rel="stylesheet"  href="{% static 'css/cadastro.css' %}">
    <h1>Cadastro</h1>
    <form method="POST" action="{% url 'cadastro_endereco' %}">
        {% csrf_token %}
        {{ form_end.as_p }}
        <button type="submit">Cadastrar</button>
    </form>
        <a href="{% url 'index' %}"><button type="button">Voltar</button></a>
    
{% endblock %}

principal/templates/html/edicao_dados.html
{% block extra_css %}
{% endblock %}
{% block content %}
<h2>Dados Pessoais</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="id_nome">Nome:</label>
        {{ form.nome }}
        <br>
        <label for="id_email">Email:</label>
        {{ form.email }}
        <br>
        <label for="id_telefone">Telefone:</label>
        {{ form.telefone }}
        <br>
        <label for="id_genero">Gênero:</label>
        {{ form.genero }}
        <br>
        <label for="id_data_nascimento">Data de nascimento:</label>
        {{ form.data_nascimento }}
        <br>
        <a href="{% url 'index' %}"><button type="submit">Salvar</button></a>
    </form>
    
{% endblock %}

principal/templates/html/er403.html
<p>403</p>
<p>Erro, permissão do recurso não permitido</p>

principal/templates/html/er404.html
<p>404</p>
<p>Erro, pagina não encontrada</p>

principal/templates/html/er500.html
<p>500</p>
<p>Erro, falha ao acessar o servidor</p>

principal/templates/html/gestor_page.html
<h1>Pagina de gestão</h1>

<form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Sair</button>
</form>

principal/templates/html/index.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <h1 class="logo">Bem vindo</h1>
{% endblock %}

principal/templates/html/login.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <link rel="stylesheet"  href="{% static 'css/login.css' %}">
    <h1>Login</h1>
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="email">Email:</label>
            <input type="text" class="form-label" id="email" name="email" required>
            <br>
            <label for="senha">Senha:</label>
            <input type="password" class="form-control" id="senha" name="senha" required>
            <br>
            <button type="submit">Entrar</button>
            <p><a href="{% url 'cadastro' %}">Cadastre</a> agora se é novo</p>
            <p>Esqueçeu a senha?<a href="{% url 'rec_senha' %}">Clique aqui</a> para recupera-la</p>
            <p><a href="{% url 'alterar_senha' %}">Alterar</a> senha</p>
        </div>
    </form>
{% endblock %}

principal/templates/html/perfil.html
{% extends "base.html" %}
{% load static %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <link rel="stylesheet"  href="{% static 'css/perfil.css' %}">
    <h1>Perfil</h1>
    <div>
        <p>Nome:{{ dados.nome }}
        <p>Gênero: {{ dados.genero }}</p>
        <p>CPF: {{ dados.cpf }}</p>
        <p>Email: {{ dados.email }}</p>
        <p>Telefone: {{ dados.telefone }}</p>
        <p>Data de nascimento: {{ dados.data_nascimento }}</p>
        <p>Nivel: {{ dados.nivel }}</p>
    </div>
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Sair</button>
    </form>
    <form method="post" action="{% url 'edicao' dados.id %}">
        {% csrf_token %}
        <button type="submit">Alterar</button>
    </form>
    <form method="post" action="{% url 'deletar' dados.id %}">
        {% csrf_token %}
        <button type="submit">Excluir conta</button>
    </form>
{% endblock %}

principal/templates/html/rec_senha.html
{% extends "base.html" %}
{% load static %}
{% block title %}Recuperar Senha{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
<link rel="stylesheet"  href="{% static 'css/rec_senha.css' %}">
<div class="container mt-5">
    <h1>Recuperar Senha</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="email" class="form-label">Digite seu e-mail:</label>
            <input type="email" class="form-control" id="email" name="email">
        </div>
        <button type="submit" class="btn btn-primary">Enviar link de recuperação</button>
        <a href="{% url 'login' %}"><button type="submit">Voltar</button></a>
    </form>
</div>
{% endblock %}